name: mdbook-generator

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.1'
          # mdbook-version: 'latest'

      - run: mdbook init
      - run: mdbook build
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply automatic changes - mdbook generated
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}